# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        os: [windows-latest, ubuntu-latest, macos-latest]
        name: [ElectroTermWin, ElectroTermLinux, ElectroTermMac]
        path: [out/make/zip/win32/x64/ElectoTerm-win32-x64-1.0.0.zip, out/make/deb/x64/electoterm_1.0.0_amd64.deb, out/make/zip/darwin]
        exclude: 
          -os: windows-latest
          name: ElectroTermLinux
          -os: windows-latest
          name: ElectroTermMac
          -os: windows-latest
          path: out/make/deb/x64/electoterm_1.0.0_amd64.deb
          -os: windows-latest
          path: out/make/zip/darwin
          -os: ubuntu-latest
          name: ElectroTermWin
          -os: ubuntu-latest
          name: ElectroTermMac
          -os: ubuntu-latest
          path: out/make/zip/win32/x64/ElectoTerm-win32-x64-1.0.0.zip
          -os: ubuntu-latest
          path: out/make/zip/darwin
          -os: macos-latest
          name: ElectroTermWin
          -os: macos-latest
          name: ElectroTermLinux
          -os: macos-latest
          path: out/make/zip/win32/x64/ElectoTerm-win32-x64-1.0.0.zip
          -os: macos-latest
          path: out/make/deb/x64/electoterm_1.0.0_amd64.deb
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run make
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.path }}
        retention-days: 1
